title: Johnweii25's Homepage
page-top-title: Johnweii25
top-section-bg-text: Be the One and Only
home-subtitle: Johnweii25&ensp;|&ensp;福本莉子
copyright-text: '&copy; Johnweii25 2023-2025. All Rights Reserved.'
