title: Johnweii25's Homepage
page-top-title: Wei Dou&ensp;|&ensp;John
top-section-bg-text: Be the One and Only
home-subtitle: Wei Dou&ensp;|&ensp;John
copyright-text: '&copy; Johnweii25 2023-2025. All Rights Reserved.'
